[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"
changelog = "docs/CHANGELOG.md"

title = "so_arm_starter Extension"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description="Extension for SO-ARM Starter Simulation and Training"
repository = "https://github.com/nvidia/isaac-lab-extensions.git"
keywords = ["extension", "robotic", "SO-ARM", "isaaclab", "healthcare"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "so_arm_starter_ext"

[isaaclab_settings]
